# Generated by Django 5.0.2 on 2024-03-05 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postfile',
            old_name='image',
            new_name='path',
        ),
    ]
