# Generated by Django 5.0.2 on 2024-02-29 15:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('member_name', models.CharField(blank=True, max_length=20, null=True)),
                ('member_birth', models.DateField(null=True)),
                ('member_phone', models.CharField(max_length=11, null=True)),
                ('member_id', models.CharField(max_length=20, null=True)),
                ('member_email', models.CharField(max_length=50)),
                ('member_password', models.TextField(null=True)),
                ('member_type', models.TextField(default='project')),
            ],
            options={
                'db_table': 'tbl_member',
            },
        ),
        migrations.CreateModel(
            name='MemberFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('path', models.ImageField(upload_to='member/%Y/%m/%d')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='member.member')),
            ],
            options={
                'db_table': 'tbl_member_file',
            },
        ),
    ]
